# Generated by Django 4.0.4 on 2022-04-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images')),
                ('name', models.CharField(max_length=100)),
                ('star', models.IntegerField()),
                ('price', models.CharField(max_length=100)),
                ('descriotions', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
            ],
        ),
    ]
