# Generated by Django 4.0.4 on 2022-05-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_detail', '0003_category_information_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(null=True),
        ),
    ]
