# Generated by Django 4.0.4 on 2022-05-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_detail', '0005_rename_category_category_cat_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ManyToManyField(null=True, to='post_detail.category'),
        ),
    ]
