# Generated by Django 4.0.4 on 2022-05-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_detail', '0006_remove_category_parent_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ManyToManyField(blank=True, null=True, to='post_detail.category'),
        ),
    ]
