# Generated by Django 4.0.4 on 2022-05-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_detail', '0007_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
