# Generated by Django 4.0.4 on 2022-06-05 15:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_detail', '0009_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
