# Generated by Django 4.0.4 on 2022-06-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_detail', '0011_productvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='is_delete',
            field=models.BooleanField(null=True),
        ),
    ]
