# Generated by Django 4.0.4 on 2023-04-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_detail', '0013_alter_information_options_alter_information_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
