# Generated by Django 4.0.4 on 2022-04-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteSetting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='address1',
            field=models.CharField(max_length=50, null=True, verbose_name='address1'),
        ),
        migrations.AddField(
            model_name='setting',
            name='address2',
            field=models.CharField(max_length=50, null=True, verbose_name='address2'),
        ),
        migrations.AddField(
            model_name='setting',
            name='copyright',
            field=models.TextField(null=True, verbose_name='copy right'),
        ),
        migrations.AddField(
            model_name='setting',
            name='email1',
            field=models.EmailField(max_length=50, null=True, verbose_name='email1'),
        ),
        migrations.AddField(
            model_name='setting',
            name='email2',
            field=models.CharField(max_length=50, null=True, verbose_name='email2'),
        ),
        migrations.AddField(
            model_name='setting',
            name='ismain',
            field=models.BooleanField(null=True, verbose_name='main setting'),
        ),
        migrations.AddField(
            model_name='setting',
            name='phone1',
            field=models.CharField(max_length=50, null=True, verbose_name='phone1'),
        ),
        migrations.AddField(
            model_name='setting',
            name='phone2',
            field=models.CharField(max_length=50, null=True, verbose_name='phone2'),
        ),
        migrations.AddField(
            model_name='setting',
            name='sitename',
            field=models.CharField(max_length=50, null=True, verbose_name='site name'),
        ),
        migrations.AddField(
            model_name='setting',
            name='siteurl',
            field=models.CharField(max_length=50, null=True, verbose_name='site url'),
        ),
    ]
