# Generated by Django 4.0.4 on 2022-06-05 15:18

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_slide_off_slide_shoplink_slide_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('description', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('shoplink', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='slide',
        ),
    ]
