# Generated by Django 4.0.4 on 2022-06-05 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_slider_delete_slide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='shoplink',
            new_name='url',
        ),
    ]
